### ISSUE TITLE
globally fix talk title case

### ISSUE THREAD

**Issue by jnicho02** [osmfoundation/sotm2019-booklet#12]
The titles of talks have inconsistent capitalisation.

"CyclOSM, a bicycle oriented render for every cyclist"
vs
"VR Map: Using OSM Data In a WebVR Environment"

or is that "VR Map: Using OSM **d**ata **i**n a WebVR **e**nvironment"?

Picky, I know.

**Comment by boothym** [comment]
There is also: "Mapathons and Imports represent a Quality Challenge for the OSM community. This presentation focuses on Buildings. It presents Metrics and show**[s]** progress of tools development to monitor and correct Quality problems in the OSM database or before importing." Sunday 12:00, page 33
