### ISSUE TITLE
reword some of "Using OSMCha to understand bad edits" in sunday.tex

### ISSUE THREAD

**Issue by jnicho02** [osmfoundation/sotm2019-booklet#13]
I think they/we should reword the section "...OSMCha, an open service that allows us to check low-quality changes that are made by the members of the OSM project in a shared database."

It sounds a bit finger-pointy to me and could be interpreted badly.

**Comment by Nakaner** [comment]
I prefer not to edit the style too much and to focus on grammar, spelling and punctuation. Otherwise we end up with rewriting some "we are sooooooo great" descriptions as well. :-/

**Comment by jnicho02** [comment]
it's more meaning... do they mean *all* changes made by *all* members of the OSM project are low-quality, or *some*? I know they mean *some* by *some* members but it can be interpreted otherwise. I find one of the interpretations offensive...or is it just me?

**Comment by Nakaner** [comment]
I decided not to ask the authors in order to get the booklet finished.
