### ISSUE TITLE
Proofreading suggestions

### ISSUE THREAD

**Issue by boothym** [osmfoundation/sotm2019-booklet#15]
Came here from the talk-gb post. Agree with the things @jnicho02 has covered in his PR. Hope you don't mind me leaving comments here, not familiar with the code format and don't know how it works with someone else already having done a PR.

Not sure if you want to edit all of the descriptions, but if you do - then searching for "iza" and "ize" then replacing the z with an s should make it even more British 😄 

**Welcome**

for "their support to" the OpenStreetMap Foundation - change to "supporting"

**Saturday**

- nonprofit - hyphenate?
- with **AN** open source solution named RoboSat.pink - add "an", possibly hyphenate open-source
- offline first - hyphenate?
- Observe makes field surveying, and verification - remove comma

**Sunday**

- multi-years - seems like it should be singular "year"?
- how some "daily life" examples - change to "everyday"
- Travelers - change to Travellers
- straight foreward as one migth hope - straightforward as one might hope
- railroad - change to railway

Not read Monday yet, but one thing I did notice was the word "Caretography" - assume that's a typo?

**Comment by jnicho02** [comment]
I've added to my Saturday pr #11 for the 4 points made about Saturday

**Comment by jnicho02** [comment]
I've added to my Welcome pr #10 for "supporting"

**Comment by jnicho02** [comment]
I've added to my Sunday pr #14 

"railroad" is in Monday

**Comment by jnicho02** [comment]
I don't have the power to close this issue, but all the points have been actioned.
