### ISSUE TITLE
QR Code for Giggity

### ISSUE THREAD

**Issue by Zverik** [osmfoundation/sotm2019-booklet#17]
I suggest adding a QR Code for the Giggity app, so participants could load the schedule onto their phones. I believe the app will have "SotM 2019" already on the list.

The link is https://play.google.com/store/apps/details?id=net.gaast.giggity

**Comment by Zverik** [comment]
Also it'd be great to add a QR Code for an iCalendar version of the schedule for iPhone / iPad users. I've just tested that it works. The link will be (not yet published) http://sotm.osmz.ru/19.ics

**Comment by Nakaner** [comment]
Thank you for the suggestion.

Your ICS file is a merge of the general and the academic track?

These are the publicly accessible ICS files for the two tracks generated by Pretalx.

https://pretalx.com/sotm2019-at/schedule/export/schedule.ics

https://pretalx.com/sotm2019/schedule/export/schedule.ics

**Comment by Zverik** [comment]
Yes, there will be a merged ics schedule as well — after I finish https://github.com/Zverik/schedule-convert/issues/1

**Comment by Zverik** [comment]
ics file is there.

**Comment by tyrasd** [comment]
this ticket can be closed now, right?
