### ISSUE TITLE
globally replace "iza" and "ize"

### ISSUE THREAD

**Issue by jnicho02** [osmfoundation/sotm2019-booklet#19]
British English is "isa" and "ise"

**Comment by boothym** [comment]
I assume it won't be a "mechanical" find/replace, as I found two people's names containing "ize" 😉

**Comment by Nakaner** [comment]
I use Grep and then modify all results manually.

I stumbled about this case where it seems that I have to replace the whole word (Monday 11:30, Roland Olbricht):
> The basic idea is to **priorize** what most likely helps to get feedback   from much more of the mappers using the tags.

My dictionary says that this verb is American. I think that "prioritise" has the same meaning. What do you think?

**Comment by boothym** [comment]
That looks like it should have been "prioritize" to begin with, so you're correct to change it to "prioritise".

That talk description however could do with an issue on its own!

**Comment by Nakaner** [comment]
fixed

**Comment by boothym** [comment]
Noticed there is also an "analyzed" to be replaced
