### ISSUE TITLE
Update social event menu

### ISSUE THREAD

**Issue by Nakaner** [osmfoundation/sotm2019-booklet#2]
There are changes to the menu of the social event catering which need to be included.

**Comment by rabidllama** [comment]
I think a number of people from the local group would prefer **not** to show the actual food on the page and instead have something like "A variety of middle-eastern style dishes (including vegan) provided by a local catering company employing refugees from Syria"

**Comment by Nakaner** [comment]
If I point me to a nice party/social event stock image or such an image from any previous national or international SotM under a compatible license, I am happy to replace the menu with it.
