### ISSUE TITLE
Quotes doubled up in monday.tex

### ISSUE THREAD

**Issue by jnicho02** [osmfoundation/sotm2019-booklet#20]
The "Our Falkirk" talk has double quotes which are fine, but this Mapathon one has extra single quotes and a double quote the wrong way round:
![map](https://user-images.githubusercontent.com/16965772/63463285-c309b100-c454-11e9-9c5b-5dc40c7596a4.PNG)

_Originally posted by @boothym in https://github.com/osmfoundation/sotm2019-booklet/pull/14#issuecomment-523624605_

**Comment by boothym** [comment]
This has been fixed in the PDF however I noticed other instances on Monday - at 11:30: ”‘true”’ and 14:30:  ”‘Continue for about 200 m then turn left”’
