### ISSUE TITLE
Welcome 

### ISSUE THREAD

**Issue by boothym** [osmfoundation/sotm2019-booklet#36]
One final thing I noticed on page 3 😃 

"This booklet provides **you** essential information about the conference"

Think this should either be "provides you with essential information" OR just "provides essential information"

**Comment by Nakaner** [comment]
I'm sorry. The print shop wrote to me a few minutes ago that they started processing the order.

**Comment by boothym** [comment]
No worries, you've done a good job with the booklet. Hope SOTM all goes well.
