### ISSUE TITLE
outdated public transport map

### ISSUE THREAD

**Issue by tyrasd** [osmfoundation/sotm2019-booklet#6]
I'm not sure if you're aware of the fact that after 2019-09-11, the local public traffic situation at the main station (which is currently mostly diverted because of construction works) will be changed: 
See http://www.heidelberg-mobinetz.de/Start/Aktuelles/18_07_2019+aenderungen+im+heidelberger+bus-+und+bahn-liniennetz+nach+den+sommerferien+2019.html

This means that at the date of the SotM, the tram and bus network will be quite different from what is currently depicted in https://github.com/osmfoundation/sotm2019-booklet/blob/master/images-print/public_transport.svg and https://github.com/osmfoundation/sotm2019-booklet/blob/master/images-print/public_transport.pdf

**Comment by tyrasd** [comment]
I believe, but am not 100% sure that the following map shows the correct state after September 11: https://www.rnv-online.de/media/rnv-online.de/Fahrtinfo/Liniennetzplaene/regulaer/Liniennetzplan_HD_regulaer.pdf – it's probably best to contact RNV about this to be sure.

**Comment by Nakaner** [comment]
@tyrasd  Thank you for the hint. While searching for the end of the constructions (press wrote "September 2019" about one year ago), I found out that the current maps will be out of date during SotM. I will ask RNV and likely use the map linked by you.

**Comment by Nakaner** [comment]
The map will be up to date at the event.
