### ISSUE TITLE
improvements to overview map

### ISSUE THREAD

**Issue by tyrasd** [osmfoundation/sotm2019-booklet#8]
it would be nice if some important points of interest would be marked on the overview map as, if possible:

* conference venue
* social event venues (hebelhalle, marstall)
* important touristic sites: heidelberg castle, old bridge + bridge monkey, königstuhl, old university, maybe the Philosophenweg and Kurpfälzisches Museum, botanical garden, zoo
* the tram tracks between Römerkreis and HBF are going to be reopened at the time of the SotM and thus should be displayed on the map
* add English labels where applicable ("main station", "old town", "old bridge")
* drop label of tram station "Berufsschule", maybe add label to [S-Bahn halt "Heidelberg-Weststadt/Südstadt"](https://www.openstreetmap.org/node/3328488465)
* drop the icons for springs (the round blue rings in the forest)
* it would be nice if tram lines weren't broken at the start and end of bridges
* road connections that are going to be still under construction at the time of SotM should probably not be printed at all or more clearly marked as impassible (e.g. the bridge near Hebelhalle towards the East across the railway tracks will be closed and can't even be used on foot to get into Weststadt – currently the white dashing can't hardly be distinguished from the regular yellow road fill).

**Comment by Nakaner** [comment]
> * conference venue
> 
> * social event venues (hebelhalle, marstall)

I forgot them.

> * important touristic sites: heidelberg castle, old bridge + bridge monkey, königstuhl, old university, maybe the Philosophenweg and Kurpfälzisches Museum, botanical garden, zoo



> * the tram tracks between Römerkreis and HBF are going to be reopened at the time of the SotM and thus should be displayed on the map
> 
> * add English labels where applicable ("main station", "old town", "old bridge")

I'm sorry but that's requires much editing of the style. I already disabled level crossings, all kinds of administrative boundaries, shortened road names, merged consecutive road segments to force more labels and removed the label from the ferry.

> * drop label of tram station "Berufsschule", maybe add label to [S-Bahn halt "Heidelberg-Weststadt/Südstadt"](https://www.openstreetmap.org/node/3328488465)

The network map (it's geographic!) will be relocated near the other maps and I can't change everything in the style.

> * drop the icons for springs (the round blue rings in the forest)

on my to do list

> * it would be nice if tram lines weren't broken at the start and end of bridges

That's an upstream bug and not that easy to fix.

> * road connections that are going to be still under construction at the time of SotM should probably not be printed at all or more clearly marked as impassible (e.g. the bridge near Hebelhalle towards the East across the railway tracks will be closed and can't even be used on foot to get into Weststadt – currently the white dashing can't hardly be distinguished from the regular yellow road fill).

Hebelbrücke is the only important one, isn't it? I can place the appropriate traffic sign for constructions there but people are advised to use more or less up to date offline maps on their smartphones. :-)

**Comment by tyrasd** [comment]
> I'm sorry but that's requires much editing of the style.

Can't you instead just edit the map data instead of the style? e.g. modifying a `name` field in your database to include English text for labels where needed?

> The network map (it's geographic!) will be relocated near the other maps and I can't change everything in the style.

I'm sorry, but I don't understand. My comment was about the fact that _Berufsschule_ is a very minor tram stop and super unimportant, while the other railway halt in Weststadt is quite a bit more important to attendees of the conference.

> That's an upstream bug and not that easy to fix.

Maybe we can use gimp or other image manipulation software to fix these in a post processing step. I can give you a hand with this, if needed. :smiley: 

> Hebelbrücke is the only important one, isn't it?

That's the one that sprang into my eye, yes.

**Comment by Nakaner** [comment]
> > I'm sorry but that's requires much editing of the style.
> 
> Can't you instead just edit the map data instead of the style? e.g. modifying a `name` field in your database to include English text for labels where needed?

I intentionally don't have write permissions in that database.

> > The network map (it's geographic!) will be relocated near the other maps and I can't change everything in the style.
> 
> I'm sorry, but I don't understand. My comment was about the fact that _Berufsschule_ is a very minor tram stop and super unimportant, while the other railway halt in Weststadt is quite a bit more important to attendees of the conference.

Heidelberg Weststadt/Südstadt is a "Haltepunkt" according to §4 Abs. 8 EBO and therefore mapped as `railway=halt` in Germany. Berufsschule is a "Bahnhof" according to §4 Abs. 2 EBO and §4 ESBO and tagged as `railway=station`.

The map is a minor part of the booklet and at some points I have to stop modifying the style.

> > That's an upstream bug and not that easy to fix.
> 
> Maybe we can use gimp or other image manipulation software to fix these in a post processing step. I can give you a hand with this, if needed. smiley

You can gimp the map and I will accept the pull request if you think that this is an important issue.

**Comment by Nakaner** [comment]
> * the tram tracks between Römerkreis and HBF are going to be reopened at the time of the SotM and thus should be displayed on the map

I will change the SQL query for `railway=construction` to appear as normal.

**Comment by Nakaner** [comment]
I added a few labels and the tram tracks.
